{"name": "test_load_testing", "status": "failed", "statusDetails": {"message": "AssertionError: Нагрузочное тестирование завершилось с ошибкой\nassert 2 == 0", "trace": "@allure.feature(\"Нагрузочное тестирование\")\n    def test_load_testing():\n        result = os.system(\"locust -f locustfile.py --headless -u 100 -r 10 -t 1m\")\n>       assert result == 0, \"Нагрузочное тестирование завершилось с ошибкой\"\nE       AssertionError: Нагрузочное тестирование завершилось с ошибкой\nE       assert 2 == 0\n\ntests\\test_perfomance.py:50: AssertionError"}, "attachments": [{"name": "stderr", "source": "68312016-013b-4241-9bcc-f078627c9ebe-attachment.txt", "type": "text/plain"}], "start": 1738756613569, "stop": 1738757219074, "uuid": "296c6306-3c18-4162-93ef-fe01db9186c4", "historyId": "b16bcb8f167273202388d59d24ae8cbe", "testCaseId": "b16bcb8f167273202388d59d24ae8cbe", "fullName": "tests.test_perfomance#test_load_testing", "labels": [{"name": "feature", "value": "Нагрузочное тестирование"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_perfomance"}, {"name": "host", "value": "kachanneee"}, {"name": "thread", "value": "57848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_perfomance"}]}