{"name": "test_load_testing", "status": "failed", "statusDetails": {"message": "AssertionError: Нагрузочное тестирование завершилось с ошибкой\nassert 2 == 0", "trace": "home_setup = <pages.home_page.HomePage object at 0x0000021A8187F6E0>\n\n    @allure.feature(\"Производительность под нагрузкой\")\n    @allure.story(\"Нагрузочное тестирование\")\n    def test_load_testing(home_setup):\n        result = os.system(\"locust -f locustfile.py --headless -u 100 -r 10 -t 1m\")\n>       assert result == 0, \"Нагрузочное тестирование завершилось с ошибкой\"\nE       AssertionError: Нагрузочное тестирование завершилось с ошибкой\nE       assert 2 == 0\n\ntests\\test_perfomance.py:47: AssertionError"}, "attachments": [{"name": "stderr", "source": "228d3b43-e0ed-4c6b-a958-247ff1b73c05-attachment.txt", "type": "text/plain"}], "start": 1739181184454, "stop": 1739181788431, "uuid": "68f3464a-0173-4848-9fed-5ddb808593f2", "historyId": "b16bcb8f167273202388d59d24ae8cbe", "testCaseId": "b16bcb8f167273202388d59d24ae8cbe", "fullName": "tests.test_perfomance#test_load_testing", "labels": [{"name": "story", "value": "Нагрузочное тестирование"}, {"name": "feature", "value": "Производительность под нагрузкой"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_perfomance"}, {"name": "host", "value": "kachanneee"}, {"name": "thread", "value": "23876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_perfomance"}]}