{"name": "test_load_testing", "status": "failed", "statusDetails": {"message": "AssertionError: Нагрузочное тестирование завершилось с ошибкой\nassert 2 == 0", "trace": "@allure.feature(\"Нагрузочное тестирование\")\n    def test_load_testing():\n        result = os.system(\"locust -f locustfile.py --headless -u 100 -r 10 -t 1m\")\n>       assert result == 0, \"Нагрузочное тестирование завершилось с ошибкой\"\nE       AssertionError: Нагрузочное тестирование завершилось с ошибкой\nE       assert 2 == 0\n\ntests\\test_perfomance.py:50: AssertionError"}, "attachments": [{"name": "stderr", "source": "eb2774e6-f8ca-45ff-a15f-fef4ea899f38-attachment.txt", "type": "text/plain"}], "start": 1739019405414, "stop": 1739020010371, "uuid": "66dce827-5cad-4454-9e0a-166fa7dea92b", "historyId": "b16bcb8f167273202388d59d24ae8cbe", "testCaseId": "b16bcb8f167273202388d59d24ae8cbe", "fullName": "tests.test_perfomance#test_load_testing", "labels": [{"name": "feature", "value": "Нагрузочное тестирование"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_perfomance"}, {"name": "host", "value": "kachanneee"}, {"name": "thread", "value": "16488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_perfomance"}]}